-- TODO Set prevolvedPokemonId
INSERT INTO
  "Pokemon" ("number", "name", "form", "isLegendary", "isMythical", "isMega", "prevolvedPokemonId")
VALUES
  ('001', 'Bulbasaur', NULL, FALSE, FALSE, FALSE, NULL),
  ('002', 'Ivysaur', NULL, FALSE, FALSE, FALSE, NULL),
  ('003', 'Venusaur', NULL, FALSE, FALSE, FALSE, NULL),
  ('003', 'Venusaur', 'Mega Venusaur', FALSE, FALSE, TRUE, NULL),
  ('004', 'Charmander', NULL, FALSE, FALSE, FALSE, NULL),
  ('005', 'Charmeleon', NULL, FALSE, FALSE, FALSE, NULL),
  ('006', 'Charizard', NULL, FALSE, FALSE, FALSE, NULL),
  ('006', 'Charizard', 'Mega Charizard X', FALSE, FALSE, TRUE, NULL),
  ('006', 'Charizard', 'Mega Charizard Y', FALSE, FALSE, TRUE, NULL),
  ('007', 'Squirtle', NULL, FALSE, FALSE, FALSE, NULL),
  ('008', 'Wartortle', NULL, FALSE, FALSE, FALSE, NULL),
  ('009', 'Blastoise', NULL, FALSE, FALSE, FALSE, NULL),
  ('009', 'Blastoise', 'Mega Blastoise', FALSE, FALSE, TRUE, NULL),
  ('010', 'Caterpie', NULL, FALSE, FALSE, FALSE, NULL),
  ('011', 'Metapod', NULL, FALSE, FALSE, FALSE, NULL),
  ('012', 'Butterfree', NULL, FALSE, FALSE, FALSE, NULL),
  ('013', 'Weedle', NULL, FALSE, FALSE, FALSE, NULL),
  ('014', 'Kakuna', NULL, FALSE, FALSE, FALSE, NULL),
  ('015', 'Beedrill', NULL, FALSE, FALSE, FALSE, NULL),
  ('015', 'Beedrill', 'Mega Beedrill', FALSE, FALSE, TRUE, NULL),
  ('016', 'Pidgey', NULL, FALSE, FALSE, FALSE, NULL),
  ('017', 'Pidgeotto', NULL, FALSE, FALSE, FALSE, NULL),
  ('018', 'Pidgeot', NULL, FALSE, FALSE, FALSE, NULL),
  ('018', 'Pidgeot', 'Mega Pidgeot', FALSE, FALSE, TRUE, NULL),
  ('019', 'Rattata', NULL, FALSE, FALSE, FALSE, NULL),
  ('019', 'Rattata', 'Alolan Rattata', FALSE, FALSE, FALSE, NULL),
  ('020', 'Raticate', NULL, FALSE, FALSE, FALSE, NULL),
  ('020', 'Raticate', 'Alolan Raticate', FALSE, FALSE, FALSE, NULL),
  ('021', 'Spearow', NULL, FALSE, FALSE, FALSE, NULL),
  ('022', 'Fearow', NULL, FALSE, FALSE, FALSE, NULL),
  ('023', 'Ekans', NULL, FALSE, FALSE, FALSE, NULL),
  ('024', 'Arbok', NULL, FALSE, FALSE, FALSE, NULL),
  ('025', 'Pikachu', NULL, FALSE, FALSE, FALSE, NULL),
  ('026', 'Raichu', NULL, FALSE, FALSE, FALSE, NULL),
  ('026', 'Raichu', 'Alolan Raichu', FALSE, FALSE, FALSE, NULL),
  ('027', 'Sandshrew', NULL, FALSE, FALSE, FALSE, NULL),
  ('027', 'Sandshrew', 'Alolan Sandshrew', FALSE, FALSE, FALSE, NULL),
  ('028', 'Sandslash', NULL, FALSE, FALSE, FALSE, NULL),
  ('028', 'Sandslash', 'Alolan Sandslash', FALSE, FALSE, FALSE, NULL),
  ('029', 'Nidoran♀' NULL, FALSE, FALSE, FALSE, NULL),
  ('030', 'Nidorina', NULL, FALSE, FALSE, FALSE, NULL),
  ('031', 'Nidoqueen', NULL, FALSE, FALSE, FALSE, NULL),
  ('032', 'Nidoran♂' NULL, FALSE, FALSE, FALSE, NULL),
  ('033', 'Nidorino', NULL, FALSE, FALSE, FALSE, NULL),
  ('034', 'Nidoking', NULL, FALSE, FALSE, FALSE, NULL),
  ('035', 'Clefairy', NULL, FALSE, FALSE, FALSE, NULL),
  ('036', 'Clefable', NULL, FALSE, FALSE, FALSE, NULL),
  ('037', 'Vulpix', NULL, FALSE, FALSE, FALSE, NULL),
  ('037', 'Vulpix', 'Alolan Vulpix', FALSE, FALSE, FALSE, NULL),
  ('038', 'Ninetales', NULL, FALSE, FALSE, FALSE, NULL),
  ('038', 'Ninetales', 'Alolan Ninetales', FALSE, FALSE, FALSE, NULL),
  ('039', 'Jigglypuff', NULL, FALSE, FALSE, FALSE, NULL),
  ('040', 'Wigglytuff', NULL, FALSE, FALSE, FALSE, NULL),
  ('041', 'Zubat', NULL, FALSE, FALSE, FALSE, NULL),
  ('042', 'Golbat', NULL, FALSE, FALSE, FALSE, NULL),
  ('043', 'Oddish', NULL, FALSE, FALSE, FALSE, NULL),
  ('044', 'Gloom', NULL, FALSE, FALSE, FALSE, NULL),
  ('045', 'Vileplume', NULL, FALSE, FALSE, FALSE, NULL),
  ('046', 'Paras', NULL, FALSE, FALSE, FALSE, NULL),
  ('047', 'Parasect', NULL, FALSE, FALSE, FALSE, NULL),
  ('048', 'Venonat', NULL, FALSE, FALSE, FALSE, NULL),
  ('049', 'Venomoth', NULL, FALSE, FALSE, FALSE, NULL),
  ('050', 'Diglett', NULL, FALSE, FALSE, FALSE, NULL),
  ('050', 'Diglett', 'Alolan Diglett', FALSE, FALSE, FALSE, NULL),
  ('051', 'Dugtrio', NULL, FALSE, FALSE, FALSE, NULL),
  ('051', 'Dugtrio', 'Alolan Dugtrio', FALSE, FALSE, FALSE, NULL),
  ('052', 'Meowth', NULL, FALSE, FALSE, FALSE, NULL),
  ('052', 'Meowth', 'Alolan Meowth', FALSE, FALSE, FALSE, NULL),
  ('053', 'Persian', NULL, FALSE, FALSE, FALSE, NULL),
  ('053', 'Persian', 'Alolan Persian', FALSE, FALSE, FALSE, NULL),
  ('054', 'Psyduck', NULL, FALSE, FALSE, FALSE, NULL),
  ('055', 'Golduck', NULL, FALSE, FALSE, FALSE, NULL),
  ('056', 'Mankey', NULL, FALSE, FALSE, FALSE, NULL),
  ('057', 'Primeape', NULL, FALSE, FALSE, FALSE, NULL),
  ('058', 'Growlithe', NULL, FALSE, FALSE, FALSE, NULL),
  ('059', 'Arcanine', NULL, FALSE, FALSE, FALSE, NULL),
  ('060', 'Poliwag', NULL, FALSE, FALSE, FALSE, NULL),
  ('061', 'Poliwhirl', NULL, FALSE, FALSE, FALSE, NULL),
  ('062', 'Poliwrath', NULL, FALSE, FALSE, FALSE, NULL),
  ('063', 'Abra', NULL, FALSE, FALSE, FALSE, NULL),
  ('064', 'Kadabra', NULL, FALSE, FALSE, FALSE, NULL),
  ('065', 'Alakazam', NULL, FALSE, FALSE, FALSE, NULL),
  ('065', 'Alakazam', 'Mega Alakazam', FALSE, FALSE, TRUE, NULL),
  ('066', 'Machop', NULL, FALSE, FALSE, FALSE, NULL),
  ('067', 'Machoke', NULL, FALSE, FALSE, FALSE, NULL),
  ('068', 'Machamp', NULL, FALSE, FALSE, FALSE, NULL),
  ('069', 'Bellsprout', NULL, FALSE, FALSE, FALSE, NULL),
  ('070', 'Weepinbell', NULL, FALSE, FALSE, FALSE, NULL),
  ('071', 'Victreebel', NULL, FALSE, FALSE, FALSE, NULL),
  ('072', 'Tentacool', NULL, FALSE, FALSE, FALSE, NULL),
  ('073', 'Tentacruel', NULL, FALSE, FALSE, FALSE, NULL),
  ('074', 'Geodude', NULL, FALSE, FALSE, FALSE, NULL),
  ('074', 'Geodude', 'Alolan Geodude', FALSE, FALSE, FALSE, NULL),
  ('075', 'Graveler', NULL, FALSE, FALSE, FALSE, NULL),
  ('075', 'Graveler', 'Alolan Graveler', FALSE, FALSE, FALSE, NULL),
  ('076', 'Golem', NULL, FALSE, FALSE, FALSE, NULL),
  ('076', 'Golem', 'Alolan Golem', FALSE, FALSE, FALSE, NULL),
  ('077', 'Ponyta', NULL, FALSE, FALSE, FALSE, NULL),
  ('078', 'Rapidash', NULL, FALSE, FALSE, FALSE, NULL),
  ('079', 'Slowpoke', NULL, FALSE, FALSE, FALSE, NULL),
  ('080', 'Slowbro', NULL, FALSE, FALSE, FALSE, NULL),
  ('080', 'Slowbro', 'Mega Slowbro', FALSE, FALSE, TRUE, NULL),
  ('081', 'Magnemite', NULL, FALSE, FALSE, FALSE, NULL),
  ('082', 'Magneton', NULL, FALSE, FALSE, FALSE, NULL),
  ('083', 'Farfetch''d', NULL, FALSE, FALSE, FALSE, NULL),
  ('084', 'Doduo', NULL, FALSE, FALSE, FALSE, NULL),
  ('085', 'Dodrio', NULL, FALSE, FALSE, FALSE, NULL),
  ('086', 'Seel', NULL, FALSE, FALSE, FALSE, NULL),
  ('087', 'Dewgong', NULL, FALSE, FALSE, FALSE, NULL),
  ('088', 'Grimer', NULL, FALSE, FALSE, FALSE, NULL),
  ('088', 'Grimer', 'Alolan Grimer', FALSE, FALSE, FALSE, NULL),
  ('089', 'Muk', NULL, FALSE, FALSE, FALSE, NULL),
  ('089', 'Muk', 'Alolan Muk', FALSE, FALSE, FALSE, NULL),
  ('090', 'Shellder', NULL, FALSE, FALSE, FALSE, NULL),
  ('091', 'Cloyster', NULL, FALSE, FALSE, FALSE, NULL),
  ('092', 'Gastly', NULL, FALSE, FALSE, FALSE, NULL),
  ('093', 'Haunter', NULL, FALSE, FALSE, FALSE, NULL),
  ('094', 'Gengar', NULL, FALSE, FALSE, FALSE, NULL),
  ('094', 'Gengar', 'Mega Gengar', FALSE, FALSE, TRUE, NULL),
  ('095', 'Onix', NULL, FALSE, FALSE, FALSE, NULL),
  ('096', 'Drowzee', NULL, FALSE, FALSE, FALSE, NULL),
  ('097', 'Hypno', NULL, FALSE, FALSE, FALSE, NULL),
  ('098', 'Krabby', NULL, FALSE, FALSE, FALSE, NULL),
  ('099', 'Kingler', NULL, FALSE, FALSE, FALSE, NULL),
  ('100', 'Voltorb', NULL, FALSE, FALSE, FALSE, NULL),
  ('101', 'Electrode', NULL, FALSE, FALSE, FALSE, NULL),
  ('102', 'Exeggcute', NULL, FALSE, FALSE, FALSE, NULL),
  ('103', 'Exeggutor', NULL, FALSE, FALSE, FALSE, NULL),
  ('103', 'Exeggutor', 'Alolan Exeggutor', FALSE, FALSE, FALSE, NULL),
  ('104', 'Cubone', NULL, FALSE, FALSE, FALSE, NULL),
  ('105', 'Marowak', NULL, FALSE, FALSE, FALSE, NULL),
  ('105', 'Marowak', 'Alolan Marowak', FALSE, FALSE, FALSE, NULL),
  ('106', 'Hitmonlee', NULL, FALSE, FALSE, FALSE, NULL),
  ('107', 'Hitmonchan', NULL, FALSE, FALSE, FALSE, NULL),
  ('108', 'Lickitung', NULL, FALSE, FALSE, FALSE, NULL),
  ('109', 'Koffing', NULL, FALSE, FALSE, FALSE, NULL),
  ('110', 'Weezing', NULL, FALSE, FALSE, FALSE, NULL),
  ('111', 'Rhyhorn', NULL, FALSE, FALSE, FALSE, NULL),
  ('112', 'Rhydon', NULL, FALSE, FALSE, FALSE, NULL),
  ('113', 'Chansey', NULL, FALSE, FALSE, FALSE, NULL),
  ('114', 'Tangela', NULL, FALSE, FALSE, FALSE, NULL),
  ('115', 'Kangaskhan', NULL, FALSE, FALSE, FALSE, NULL),
  ('115', 'Kangaskhan', 'Mega Kangaskhan', FALSE, FALSE, TRUE, NULL),
  ('116', 'Horsea', NULL, FALSE, FALSE, FALSE, NULL),
  ('117', 'Seadra', NULL, FALSE, FALSE, FALSE, NULL),
  ('118', 'Goldeen', NULL, FALSE, FALSE, FALSE, NULL),
  ('119', 'Seaking', NULL, FALSE, FALSE, FALSE, NULL),
  ('120', 'Staryu', NULL, FALSE, FALSE, FALSE, NULL),
  ('121', 'Starmie', NULL, FALSE, FALSE, FALSE, NULL),
  ('122', 'Mr. Mime', NULL, FALSE, FALSE, FALSE, NULL),
  ('123', 'Scyther', NULL, FALSE, FALSE, FALSE, NULL),
  ('124', 'Jynx', NULL, FALSE, FALSE, FALSE, NULL),
  ('125', 'Electabuzz', NULL, FALSE, FALSE, FALSE, NULL),
  ('126', 'Magmar', NULL, FALSE, FALSE, FALSE, NULL),
  ('127', 'Pinsir', NULL, FALSE, FALSE, FALSE, NULL),
  ('127', 'Pinsir', 'Mega Pinsir', FALSE, FALSE, TRUE, NULL),
  ('128', 'Tauros', NULL, FALSE, FALSE, FALSE, NULL),
  ('129', 'Magikarp', NULL, FALSE, FALSE, FALSE, NULL),
  ('130', 'Gyarados', NULL, FALSE, FALSE, FALSE, NULL),
  ('130', 'Gyarados', 'Mega Gyarados', FALSE, FALSE, TRUE, NULL),
  ('131', 'Lapras', NULL, FALSE, FALSE, FALSE, NULL),
  ('132', 'Ditto', NULL, FALSE, FALSE, FALSE, NULL),
  ('133', 'Eevee', NULL, FALSE, FALSE, FALSE, NULL),
  ('134', 'Vaporeon', NULL, FALSE, FALSE, FALSE, NULL),
  ('135', 'Jolteon', NULL, FALSE, FALSE, FALSE, NULL),
  ('136', 'Flareon', NULL, FALSE, FALSE, FALSE, NULL),
  ('137', 'Porygon', NULL, FALSE, FALSE, FALSE, NULL),
  ('138', 'Omanyte', NULL, FALSE, FALSE, FALSE, NULL),
  ('139', 'Omastar', NULL, FALSE, FALSE, FALSE, NULL),
  ('140', 'Kabuto', NULL, FALSE, FALSE, FALSE, NULL),
  ('141', 'Kabutops', NULL, FALSE, FALSE, FALSE, NULL),
  ('142', 'Aerodactyl', NULL, FALSE, FALSE, FALSE, NULL),
  ('142', 'Aerodactyl', 'Mega Aerodactyl', FALSE, FALSE, TRUE, NULL),
  ('143', 'Snorlax', NULL, FALSE, FALSE, FALSE, NULL),
  ('144', 'Articuno', NULL, FALSE, FALSE, FALSE, NULL),
  ('145', 'Zapdos', NULL, FALSE, FALSE, FALSE, NULL),
  ('146', 'Moltres', NULL, FALSE, FALSE, FALSE, NULL),
  ('147', 'Dratini', NULL, FALSE, FALSE, FALSE, NULL),
  ('148', 'Dragonair', NULL, FALSE, FALSE, FALSE, NULL),
  ('149', 'Dragonite', NULL, FALSE, FALSE, FALSE, NULL),
  ('150', 'Mewtwo', NULL, TRUE, FALSE, FALSE, NULL),
  ('150', 'Mewtwo', 'Mega Mewtwo X', TRUE, FALSE, TRUE, NULL),
  ('150', 'Mewtwo', 'Mega Mewtwo Y', TRUE, FALSE, TRUE, NULL),
  ('151', 'Mew', NULL, FALSE, TRUE, FALSE, NULL),
  ('152', 'Chikorita', NULL, FALSE, FALSE, FALSE, NULL),
  ('153', 'Bayleef', NULL, FALSE, FALSE, FALSE, NULL),
  ('154', 'Meganium', NULL, FALSE, FALSE, FALSE, NULL),
  ('155', 'Cyndaquil', NULL, FALSE, FALSE, FALSE, NULL),
  ('156', 'Quilava', NULL, FALSE, FALSE, FALSE, NULL),
  ('157', 'Typhlosion', NULL, FALSE, FALSE, FALSE, NULL),
  ('158', 'Totodile', NULL, FALSE, FALSE, FALSE, NULL),
  ('159', 'Croconaw', NULL, FALSE, FALSE, FALSE, NULL),
  ('160', 'Feraligatr', NULL, FALSE, FALSE, FALSE, NULL),
  ('161', 'Sentret', NULL, FALSE, FALSE, FALSE, NULL),
  ('162', 'Furret', NULL, FALSE, FALSE, FALSE, NULL),
  ('163', 'Hoothoot', NULL, FALSE, FALSE, FALSE, NULL),
  ('164', 'Noctowl', NULL, FALSE, FALSE, FALSE, NULL),
  ('165', 'Ledyba', NULL, FALSE, FALSE, FALSE, NULL),
  ('166', 'Ledian', NULL, FALSE, FALSE, FALSE, NULL),
  ('167', 'Spinarak', NULL, FALSE, FALSE, FALSE, NULL),
  ('168', 'Ariados', NULL, FALSE, FALSE, FALSE, NULL),
  ('169', 'Crobat', NULL, FALSE, FALSE, FALSE, NULL),
  ('170', 'Chinchou', NULL, FALSE, FALSE, FALSE, NULL),
  ('171', 'Lanturn', NULL, FALSE, FALSE, FALSE, NULL),
  ('172', 'Pichu', NULL, FALSE, FALSE, FALSE, NULL),
  ('173', 'Cleffa', NULL, FALSE, FALSE, FALSE, NULL),
  ('174', 'Igglybuff', NULL, FALSE, FALSE, FALSE, NULL),
  ('175', 'Togepi', NULL, FALSE, FALSE, FALSE, NULL),
  ('176', 'Togetic', NULL, FALSE, FALSE, FALSE, NULL),
  ('177', 'Natu', NULL, FALSE, FALSE, FALSE, NULL),
  ('178', 'Xatu', NULL, FALSE, FALSE, FALSE, NULL),
  ('179', 'Mareep', NULL, FALSE, FALSE, FALSE, NULL),
  ('180', 'Flaaffy', NULL, FALSE, FALSE, FALSE, NULL),
  ('181', 'Ampharos', NULL, FALSE, FALSE, FALSE, NULL),
  ('181', 'Ampharos', 'Mega Ampharos', FALSE, FALSE, TRUE, NULL),
  ('182', 'Bellossom', NULL, FALSE, FALSE, FALSE, NULL),
  ('183', 'Marill', NULL, FALSE, FALSE, FALSE, NULL),
  ('184', 'Azumarill', NULL, FALSE, FALSE, FALSE, NULL),
  ('185', 'Sudowoodo', NULL, FALSE, FALSE, FALSE, NULL),
  ('186', 'Politoed', NULL, FALSE, FALSE, FALSE, NULL),
  ('187', 'Hoppip', NULL, FALSE, FALSE, FALSE, NULL),
  ('188', 'Skiploom', NULL, FALSE, FALSE, FALSE, NULL),
  ('189', 'Jumpluff', NULL, FALSE, FALSE, FALSE, NULL),
  ('190', 'Aipom', NULL, FALSE, FALSE, FALSE, NULL),
  ('191', 'Sunkern', NULL, FALSE, FALSE, FALSE, NULL),
  ('192', 'Sunflora', NULL, FALSE, FALSE, FALSE, NULL),
  ('193', 'Yanma', NULL, FALSE, FALSE, FALSE, NULL),
  ('194', 'Wooper', NULL, FALSE, FALSE, FALSE, NULL),
  ('195', 'Quagsire', NULL, FALSE, FALSE, FALSE, NULL),
  ('196', 'Espeon', NULL, FALSE, FALSE, FALSE, NULL),
  ('197', 'Umbreon', NULL, FALSE, FALSE, FALSE, NULL),
  ('198', 'Murkrow', NULL, FALSE, FALSE, FALSE, NULL),
  ('199', 'Slowking', NULL, FALSE, FALSE, FALSE, NULL),
  ('200', 'Misdreavus', NULL, FALSE, FALSE, FALSE, NULL),
  ('201', 'Unown', NULL, FALSE, FALSE, FALSE, NULL),
  ('202', 'Wobbuffet', NULL, FALSE, FALSE, FALSE, NULL),
  ('203', 'Girafarig', NULL, FALSE, FALSE, FALSE, NULL),
  ('204', 'Pineco', NULL, FALSE, FALSE, FALSE, NULL),
  ('205', 'Forretress', NULL, FALSE, FALSE, FALSE, NULL),
  ('206', 'Dunsparce', NULL, FALSE, FALSE, FALSE, NULL),
  ('207', 'Gligar', NULL, FALSE, FALSE, FALSE, NULL),
  ('208', 'Steelix', NULL, FALSE, FALSE, FALSE, NULL),
  ('208', 'Steelix', 'Mega Steelix', FALSE, FALSE, TRUE, NULL),
  ('209', 'Snubbull', NULL, FALSE, FALSE, FALSE, NULL),
  ('210', 'Granbull', NULL, FALSE, FALSE, FALSE, NULL),
  ('211', 'Qwilfish', NULL, FALSE, FALSE, FALSE, NULL),
  ('212', 'Scizor', NULL, FALSE, FALSE, FALSE, NULL),
  ('212', 'Scizor', 'Mega Scizor', FALSE, FALSE, TRUE, NULL),
  ('213', 'Shuckle', NULL, FALSE, FALSE, FALSE, NULL),
  ('214', 'Heracross', NULL, FALSE, FALSE, FALSE, NULL),
  ('214', 'Heracross', 'Mega Heracross', FALSE, FALSE, TRUE, NULL),
  ('215', 'Sneasel', NULL, FALSE, FALSE, FALSE, NULL),
  ('216', 'Teddiursa', NULL, FALSE, FALSE, FALSE, NULL),
  ('217', 'Ursaring', NULL, FALSE, FALSE, FALSE, NULL),
  ('218', 'Slugma', NULL, FALSE, FALSE, FALSE, NULL),
  ('219', 'Magcargo', NULL, FALSE, FALSE, FALSE, NULL),
  ('220', 'Swinub', NULL, FALSE, FALSE, FALSE, NULL),
  ('221', 'Piloswine', NULL, FALSE, FALSE, FALSE, NULL),
  ('222', 'Corsola', NULL, FALSE, FALSE, FALSE, NULL),
  ('223', 'Remoraid', NULL, FALSE, FALSE, FALSE, NULL),
  ('224', 'Octillery', NULL, FALSE, FALSE, FALSE, NULL),
  ('225', 'Delibird', NULL, FALSE, FALSE, FALSE, NULL),
  ('226', 'Mantine', NULL, FALSE, FALSE, FALSE, NULL),
  ('227', 'Skarmory', NULL, FALSE, FALSE, FALSE, NULL),
  ('228', 'Houndour', NULL, FALSE, FALSE, FALSE, NULL),
  ('229', 'Houndoom', NULL, FALSE, FALSE, FALSE, NULL),
  ('229', 'Houndoom', 'Mega Houndoom', FALSE, FALSE, TRUE, NULL),
  ('230', 'Kingdra', NULL, FALSE, FALSE, FALSE, NULL),
  ('231', 'Phanpy', NULL, FALSE, FALSE, FALSE, NULL),
  ('232', 'Donphan', NULL, FALSE, FALSE, FALSE, NULL),
  ('233', 'Porygon2', NULL, FALSE, FALSE, FALSE, NULL),
  ('234', 'Stantler', NULL, FALSE, FALSE, FALSE, NULL),
  ('235', 'Smeargle', NULL, FALSE, FALSE, FALSE, NULL),
  ('236', 'Tyrogue', NULL, FALSE, FALSE, FALSE, NULL),
  ('237', 'Hitmontop', NULL, FALSE, FALSE, FALSE, NULL),
  ('238', 'Smoochum', NULL, FALSE, FALSE, FALSE, NULL),
  ('239', 'Elekid', NULL, FALSE, FALSE, FALSE, NULL),
  ('240', 'Magby', NULL, FALSE, FALSE, FALSE, NULL),
  ('241', 'Miltank', NULL, FALSE, FALSE, FALSE, NULL),
  ('242', 'Blissey', NULL, FALSE, FALSE, FALSE, NULL),
  ('243', 'Raikou', NULL, FALSE, FALSE, FALSE, NULL),
  ('244', 'Entei', NULL, FALSE, FALSE, FALSE, NULL),
  ('245', 'Suicune', NULL, FALSE, FALSE, FALSE, NULL),
  ('246', 'Larvitar', NULL, FALSE, FALSE, FALSE, NULL),
  ('247', 'Pupitar', NULL, FALSE, FALSE, FALSE, NULL),
  ('248', 'Tyranitar', NULL, FALSE, FALSE, FALSE, NULL),
  ('248', 'Tyranitar', 'Mega Tyranitar', FALSE, FALSE, TRUE, NULL),
  ('249', 'Lugia', NULL, TRUE, FALSE, FALSE, NULL),
  ('250', 'Ho-oh', NULL, TRUE, FALSE, FALSE, NULL),
  ('251', 'Celebi', NULL, FALSE, TRUE, FALSE, NULL),
  ('252', 'Treecko', NULL, FALSE, FALSE, FALSE, NULL),
  ('253', 'Grovyle', NULL, FALSE, FALSE, FALSE, NULL),
  ('254', 'Sceptile', NULL, FALSE, FALSE, FALSE, NULL),
  ('254', 'Sceptile', 'Mega Sceptile', FALSE, FALSE, TRUE, NULL),
  ('255', 'Torchic', NULL, FALSE, FALSE, FALSE, NULL),
  ('256', 'Combusken', NULL, FALSE, FALSE, FALSE, NULL),
  ('257', 'Blaziken', NULL, FALSE, FALSE, FALSE, NULL),
  ('257', 'Blaziken', 'Mega Blaziken', FALSE, FALSE, TRUE, NULL),
  ('258', 'Mudkip', NULL, FALSE, FALSE, FALSE, NULL),
  ('259', 'Marshtomp', NULL, FALSE, FALSE, FALSE, NULL),
  ('260', 'Swampert', NULL, FALSE, FALSE, FALSE, NULL),
  ('260', 'Swampert', 'Mega Swampert', FALSE, FALSE, TRUE, NULL),
  ('261', 'Poochyena', NULL, FALSE, FALSE, FALSE, NULL),
  ('262', 'Mightyena', NULL, FALSE, FALSE, FALSE, NULL),
  ('263', 'Zigzagoon', NULL, FALSE, FALSE, FALSE, NULL),
  ('264', 'Linoone', NULL, FALSE, FALSE, FALSE, NULL),
  ('265', 'Wurmple', NULL, FALSE, FALSE, FALSE, NULL),
  ('266', 'Silcoon', NULL, FALSE, FALSE, FALSE, NULL),
  ('267', 'Beautifly', NULL, FALSE, FALSE, FALSE, NULL),
  ('268', 'Cascoon', NULL, FALSE, FALSE, FALSE, NULL),
  ('269', 'Dustox', NULL, FALSE, FALSE, FALSE, NULL),
  ('270', 'Lotad', NULL, FALSE, FALSE, FALSE, NULL),
  ('271', 'Lombre', NULL, FALSE, FALSE, FALSE, NULL),
  ('272', 'Ludicolo', NULL, FALSE, FALSE, FALSE, NULL),
  ('273', 'Seedot', NULL, FALSE, FALSE, FALSE, NULL),
  ('274', 'Nuzleaf', NULL, FALSE, FALSE, FALSE, NULL),
  ('275', 'Shiftry', NULL, FALSE, FALSE, FALSE, NULL),
  ('276', 'Taillow', NULL, FALSE, FALSE, FALSE, NULL),
  ('277', 'Swellow', NULL, FALSE, FALSE, FALSE, NULL),
  ('278', 'Wingull', NULL, FALSE, FALSE, FALSE, NULL),
  ('279', 'Pelipper', NULL, FALSE, FALSE, FALSE, NULL),
  ('280', 'Ralts', NULL, FALSE, FALSE, FALSE, NULL),
  ('281', 'Kirlia', NULL, FALSE, FALSE, FALSE, NULL),
  ('282', 'Gardevoir', NULL, FALSE, FALSE, FALSE, NULL),
  ('282', 'Gardevoir', 'Mega Gardevoir', FALSE, FALSE, TRUE, NULL),
  ('283', 'Surskit', NULL, FALSE, FALSE, FALSE, NULL),
  ('284', 'Masquerain', NULL, FALSE, FALSE, FALSE, NULL),
  ('285', 'Shroomish', NULL, FALSE, FALSE, FALSE, NULL),
  ('286', 'Breloom', NULL, FALSE, FALSE, FALSE, NULL),
  ('287', 'Slakoth', NULL, FALSE, FALSE, FALSE, NULL),
  ('288', 'Vigoroth', NULL, FALSE, FALSE, FALSE, NULL),
  ('289', 'Slaking', NULL, FALSE, FALSE, FALSE, NULL),
  ('290', 'Nincada', NULL, FALSE, FALSE, FALSE, NULL),
  ('291', 'Ninjask', NULL, FALSE, FALSE, FALSE, NULL),
  ('292', 'Shedinja', NULL, FALSE, FALSE, FALSE, NULL),
  ('293', 'Whismur', NULL, FALSE, FALSE, FALSE, NULL),
  ('294', 'Loudred', NULL, FALSE, FALSE, FALSE, NULL),
  ('295', 'Exploud', NULL, FALSE, FALSE, FALSE, NULL),
  ('296', 'Makuhita', NULL, FALSE, FALSE, FALSE, NULL),
  ('297', 'Hariyama', NULL, FALSE, FALSE, FALSE, NULL),
  ('298', 'Azurill', NULL, FALSE, FALSE, FALSE, NULL),
  ('299', 'Nosepass', NULL, FALSE, FALSE, FALSE, NULL),
  ('300', 'Skitty', NULL, FALSE, FALSE, FALSE, NULL),
  ('301', 'Delcatty', NULL, FALSE, FALSE, FALSE, NULL),
  ('302', 'Sableye', NULL, FALSE, FALSE, FALSE, NULL),
  ('302', 'Sableye', 'Mega Sableye', FALSE, FALSE, TRUE, NULL),
  ('303', 'Mawile', NULL, FALSE, FALSE, FALSE, NULL),
  ('303', 'Mawile', 'Mega Mawile', FALSE, FALSE, TRUE, NULL),
  ('304', 'Aron', NULL, FALSE, FALSE, FALSE, NULL),
  ('305', 'Lairon', NULL, FALSE, FALSE, FALSE, NULL),
  ('306', 'Aggron', NULL, FALSE, FALSE, FALSE, NULL),
  ('306', 'Aggron', 'Mega Aggron', FALSE, FALSE, TRUE, NULL),
  ('307', 'Meditite', NULL, FALSE, FALSE, FALSE, NULL),
  ('308', 'Medicham', NULL, FALSE, FALSE, FALSE, NULL),
  ('308', 'Medicham', 'Mega Medicham', FALSE, FALSE, TRUE, NULL),
  ('309', 'Electrike', NULL, FALSE, FALSE, FALSE, NULL),
  ('310', 'Manectric', NULL, FALSE, FALSE, FALSE, NULL),
  ('310', 'Manectric', 'Mega Manectric', FALSE, FALSE, TRUE, NULL),
  ('311', 'Plusle', NULL, FALSE, FALSE, FALSE, NULL),
  ('312', 'Minun', NULL, FALSE, FALSE, FALSE, NULL),
  ('313', 'Volbeat', NULL, FALSE, FALSE, FALSE, NULL),
  ('314', 'Illumise', NULL, FALSE, FALSE, FALSE, NULL),
  ('315', 'Roselia', NULL, FALSE, FALSE, FALSE, NULL),
  ('316', 'Gulpin', NULL, FALSE, FALSE, FALSE, NULL),
  ('317', 'Swalot', NULL, FALSE, FALSE, FALSE, NULL),
  ('318', 'Carvanha', NULL, FALSE, FALSE, FALSE, NULL),
  ('319', 'Sharpedo', NULL, FALSE, FALSE, FALSE, NULL),
  ('319', 'Sharpedo', 'Mega Sharpedo', FALSE, FALSE, TRUE, NULL),
  ('320', 'Wailmer', NULL, FALSE, FALSE, FALSE, NULL),
  ('321', 'Wailord', NULL, FALSE, FALSE, FALSE, NULL),
  ('322', 'Numel', NULL, FALSE, FALSE, FALSE, NULL),
  ('323', 'Camerupt', NULL, FALSE, FALSE, FALSE, NULL),
  ('323', 'Camerupt', 'Mega Camerupt', FALSE, FALSE, TRUE, NULL),
  ('324', 'Torkoal', NULL, FALSE, FALSE, FALSE, NULL),
  ('325', 'Spoink', NULL, FALSE, FALSE, FALSE, NULL),
  ('326', 'Grumpig', NULL, FALSE, FALSE, FALSE, NULL),
  ('327', 'Spinda', NULL, FALSE, FALSE, FALSE, NULL),
  ('328', 'Trapinch', NULL, FALSE, FALSE, FALSE, NULL),
  ('329', 'Vibrava', NULL, FALSE, FALSE, FALSE, NULL),
  ('330', 'Flygon', NULL, FALSE, FALSE, FALSE, NULL),
  ('331', 'Cacnea', NULL, FALSE, FALSE, FALSE, NULL),
  ('332', 'Cacturne', NULL, FALSE, FALSE, FALSE, NULL),
  ('333', 'Swablu', NULL, FALSE, FALSE, FALSE, NULL),
  ('334', 'Altaria', NULL, FALSE, FALSE, FALSE, NULL),
  ('334', 'Altaria', 'Mega Altaria', FALSE, FALSE, TRUE, NULL),
  ('335', 'Zangoose', NULL, FALSE, FALSE, FALSE, NULL),
  ('336', 'Seviper', NULL, FALSE, FALSE, FALSE, NULL),
  ('337', 'Lunatone', NULL, FALSE, FALSE, FALSE, NULL),
  ('338', 'Solrock', NULL, FALSE, FALSE, FALSE, NULL),
  ('339', 'Barboach', NULL, FALSE, FALSE, FALSE, NULL),
  ('340', 'Whiscash', NULL, FALSE, FALSE, FALSE, NULL),
  ('341', 'Corphish', NULL, FALSE, FALSE, FALSE, NULL),
  ('342', 'Crawdaunt', NULL, FALSE, FALSE, FALSE, NULL),
  ('343', 'Baltoy', NULL, FALSE, FALSE, FALSE, NULL),
  ('344', 'Claydol', NULL, FALSE, FALSE, FALSE, NULL),
  ('345', 'Lileep', NULL, FALSE, FALSE, FALSE, NULL),
  ('346', 'Cradily', NULL, FALSE, FALSE, FALSE, NULL),
  ('347', 'Anorith', NULL, FALSE, FALSE, FALSE, NULL),
  ('348', 'Armaldo', NULL, FALSE, FALSE, FALSE, NULL),
  ('349', 'Feebas', NULL, FALSE, FALSE, FALSE, NULL),
  ('350', 'Milotic', NULL, FALSE, FALSE, FALSE, NULL),
  ('351', 'Castform', NULL, FALSE, FALSE, FALSE, NULL),
  ('351', 'Castform', 'Sunny Form', FALSE, FALSE, FALSE, NULL),
  ('351', 'Castform', 'Rainy Form', FALSE, FALSE, FALSE, NULL),
  ('351', 'Castform', 'Snowy Form', FALSE, FALSE, FALSE, NULL),
  ('352', 'Kecleon', NULL, FALSE, FALSE, FALSE, NULL),
  ('353', 'Shuppet', NULL, FALSE, FALSE, FALSE, NULL),
  ('354', 'Banette', NULL, FALSE, FALSE, FALSE, NULL),
  ('354', 'Banette', 'Mega Banette', FALSE, FALSE, TRUE, NULL),
  ('355', 'Duskull', NULL, FALSE, FALSE, FALSE, NULL),
  ('356', 'Dusclops', NULL, FALSE, FALSE, FALSE, NULL),
  ('357', 'Tropius', NULL, FALSE, FALSE, FALSE, NULL),
  ('358', 'Chimecho', NULL, FALSE, FALSE, FALSE, NULL),
  ('359', 'Absol', NULL, FALSE, FALSE, FALSE, NULL),
  ('359', 'Absol', 'Mega Absol', FALSE, FALSE, TRUE, NULL),
  ('360', 'Wynaut', NULL, FALSE, FALSE, FALSE, NULL),
  ('361', 'Snorunt', NULL, FALSE, FALSE, FALSE, NULL),
  ('362', 'Glalie', NULL, FALSE, FALSE, FALSE, NULL),
  ('362', 'Glalie', 'Mega Glalie', FALSE, FALSE, TRUE, NULL),
  ('363', 'Spheal', NULL, FALSE, FALSE, FALSE, NULL),
  ('364', 'Sealeo', NULL, FALSE, FALSE, FALSE, NULL),
  ('365', 'Walrein', NULL, FALSE, FALSE, FALSE, NULL),
  ('366', 'Clamperl', NULL, FALSE, FALSE, FALSE, NULL),
  ('367', 'Huntail', NULL, FALSE, FALSE, FALSE, NULL),
  ('368', 'Gorebyss', NULL, FALSE, FALSE, FALSE, NULL),
  ('369', 'Relicanth', NULL, FALSE, FALSE, FALSE, NULL),
  ('370', 'Luvdisc', NULL, FALSE, FALSE, FALSE, NULL),
  ('371', 'Bagon', NULL, FALSE, FALSE, FALSE, NULL),
  ('372', 'Shelgon', NULL, FALSE, FALSE, FALSE, NULL),
  ('373', 'Salamence', NULL, FALSE, FALSE, FALSE, NULL),
  ('373', 'Salamence', 'Mega Salamence', FALSE, FALSE, TRUE, NULL),
  ('374', 'Beldum', NULL, FALSE, FALSE, FALSE, NULL),
  ('375', 'Metang', NULL, FALSE, FALSE, FALSE, NULL),
  ('376', 'Metagross', NULL, FALSE, FALSE, FALSE, NULL),
  ('376', 'Metagross', 'Mega Metagross', FALSE, FALSE, TRUE, NULL),
  ('377', 'Regirock', NULL, TRUE, FALSE, FALSE, NULL),
  ('378', 'Regice', NULL, TRUE, FALSE, FALSE, NULL),
  ('379', 'Registeel', NULL, TRUE, FALSE, FALSE, NULL),
  ('380', 'Latias', NULL, TRUE, FALSE, FALSE, NULL),
  ('380', 'Latias', 'Mega Latias', TRUE, FALSE, TRUE, NULL),
  ('381', 'Latios', NULL, TRUE, FALSE, FALSE, NULL),
  ('381', 'Latios', 'Mega Latios', TRUE, FALSE, TRUE, NULL),
  ('382', 'Kyogre', NULL, TRUE, FALSE, FALSE, NULL),
  ('382', 'Kyogre', 'Primal Kyogre', TRUE, TRUE), NULL),
  ('383', 'Groudon', NULL, TRUE, FALSE, FALSE, NULL),
  ('383', 'Groudon', 'Primal Groudon', TRUE, FALSE, TRUE, NULL),
  ('384', 'Rayquaza', NULL, TRUE, FALSE, FALSE, NULL),
  ('384', 'Rayquaza', 'Mega Rayquaza', TRUE, FALSE, TRUE, NULL),
  ('385', 'Jirachi', NULL, FALSE, TRUE, FALSE, NULL),
  ('386', 'Deoxys', 'Normal Forme', FALSE, TRUE, FALSE, NULL),
  ('386', 'Deoxys', 'Attack Forme', FALSE, TRUE, FALSE, NULL),
  ('386', 'Deoxys', 'Defense Forme', FALSE, TRUE, FALSE, NULL),
  ('386', 'Deoxys', 'Speed Forme', FALSE, TRUE, FALSE, NULL),
  ('387', 'Turtwig', NULL, FALSE, FALSE, FALSE, NULL),
  ('388', 'Grotle', NULL, FALSE, FALSE, FALSE, NULL),
  ('389', 'Torterra', NULL, FALSE, FALSE, FALSE, NULL),
  ('390', 'Chimchar', NULL, FALSE, FALSE, FALSE, NULL),
  ('391', 'Monferno', NULL, FALSE, FALSE, FALSE, NULL),
  ('392', 'Infernape', NULL, FALSE, FALSE, FALSE, NULL),
  ('393', 'Piplup', NULL, FALSE, FALSE, FALSE, NULL),
  ('394', 'Prinplup', NULL, FALSE, FALSE, FALSE, NULL),
  ('395', 'Empoleon', NULL, FALSE, FALSE, FALSE, NULL),
  ('396', 'Starly', NULL, FALSE, FALSE, FALSE, NULL),
  ('397', 'Staravia', NULL, FALSE, FALSE, FALSE, NULL),
  ('398', 'Staraptor', NULL, FALSE, FALSE, FALSE, NULL),
  ('399', 'Bidoof', NULL, FALSE, FALSE, FALSE, NULL),
  ('400', 'Bibarel', NULL, FALSE, FALSE, FALSE, NULL),
  ('401', 'Kricketot', NULL, FALSE, FALSE, FALSE, NULL),
  ('402', 'Kricketune', NULL, FALSE, FALSE, FALSE, NULL),
  ('403', 'Shinx', NULL, FALSE, FALSE, FALSE, NULL),
  ('404', 'Luxio', NULL, FALSE, FALSE, FALSE, NULL),
  ('405', 'Luxray', NULL, FALSE, FALSE, FALSE, NULL),
  ('406', 'Budew', NULL, FALSE, FALSE, FALSE, NULL),
  ('407', 'Roserade', NULL, FALSE, FALSE, FALSE, NULL),
  ('408', 'Cranidos', NULL, FALSE, FALSE, FALSE, NULL),
  ('409', 'Rampardos', NULL, FALSE, FALSE, FALSE, NULL),
  ('410', 'Shieldon', NULL, FALSE, FALSE, FALSE, NULL),
  ('411', 'Bastiodon', NULL, FALSE, FALSE, FALSE, NULL),
  ('412', 'Burmy', NULL, FALSE, FALSE, FALSE, NULL),
  ('413', 'Wormadam', 'Plant Cloak', FALSE, FALSE, FALSE, NULL),
  ('413', 'Wormadam', 'Sandy Cloak', FALSE, FALSE, FALSE, NULL),
  ('413', 'Wormadam', 'Trash Cloak', FALSE, FALSE, FALSE, NULL),
  ('414', 'Mothim', NULL, FALSE, FALSE, FALSE, NULL),
  ('415', 'Combee', NULL, FALSE, FALSE, FALSE, NULL),
  ('416', 'Vespiquen', NULL, FALSE, FALSE, FALSE, NULL),
  ('417', 'Pachirisu', NULL, FALSE, FALSE, FALSE, NULL),
  ('418', 'Buizel', NULL, FALSE, FALSE, FALSE, NULL),
  ('419', 'Floatzel', NULL, FALSE, FALSE, FALSE, NULL),
  ('420', 'Cherubi', NULL, FALSE, FALSE, FALSE, NULL),
  ('421', 'Cherrim', NULL, FALSE, FALSE, FALSE, NULL),
  ('422', 'Shellos', NULL, FALSE, FALSE, FALSE, NULL),
  ('423', 'Gastrodon', NULL, FALSE, FALSE, FALSE, NULL),
  ('424', 'Ambipom', NULL, FALSE, FALSE, FALSE, NULL),
  ('425', 'Drifloon', NULL, FALSE, FALSE, FALSE, NULL),
  ('426', 'Drifblim', NULL, FALSE, FALSE, FALSE, NULL),
  ('427', 'Buneary', NULL, FALSE, FALSE, FALSE, NULL),
  ('428', 'Lopunny', NULL, FALSE, FALSE, FALSE, NULL),
  ('428', 'Lopunny', 'Mega Lopunny', FALSE, FALSE, TRUE, NULL),
  ('429', 'Mismagius', NULL, FALSE, FALSE, FALSE, NULL),
  ('430', 'Honchkrow', NULL, FALSE, FALSE, FALSE, NULL),
  ('431', 'Glameow', NULL, FALSE, FALSE, FALSE, NULL),
  ('432', 'Purugly', NULL, FALSE, FALSE, FALSE, NULL),
  ('433', 'Chingling', NULL, FALSE, FALSE, FALSE, NULL),
  ('434', 'Stunky', NULL, FALSE, FALSE, FALSE, NULL),
  ('435', 'Skuntank', NULL, FALSE, FALSE, FALSE, NULL),
  ('436', 'Bronzor', NULL, FALSE, FALSE, FALSE, NULL),
  ('437', 'Bronzong', NULL, FALSE, FALSE, FALSE, NULL),
  ('438', 'Bonsly', NULL, FALSE, FALSE, FALSE, NULL),
  ('439', 'Mime Jr', NULL, FALSE, FALSE, FALSE, NULL),
  ('440', 'Happiny', NULL, FALSE, FALSE, FALSE, NULL),
  ('441', 'Chatot', NULL, FALSE, FALSE, FALSE, NULL),
  ('442', 'Spiritomb', NULL, FALSE, FALSE, FALSE, NULL),
  ('443', 'Gible', NULL, FALSE, FALSE, FALSE, NULL),
  ('444', 'Gabite', NULL, FALSE, FALSE, FALSE, NULL),
  ('445', 'Garchomp', NULL, FALSE, FALSE, FALSE, NULL),
  ('445', 'Garchomp', 'Mega Garchomp', FALSE, FALSE, TRUE, NULL),
  ('446', 'Munchlax', NULL, FALSE, FALSE, FALSE, NULL),
  ('447', 'Riolu', NULL, FALSE, FALSE, FALSE, NULL),
  ('448', 'Lucario', NULL, FALSE, FALSE, FALSE, NULL),
  ('448', 'Lucario', 'Mega Lucario', FALSE, FALSE, TRUE, NULL),
  ('449', 'Hippopotas', NULL, FALSE, FALSE, FALSE, NULL),
  ('450', 'Hippowdon', NULL, FALSE, FALSE, FALSE, NULL),
  ('451', 'Skorupi', NULL, FALSE, FALSE, FALSE, NULL),
  ('452', 'Drapion', NULL, FALSE, FALSE, FALSE, NULL),
  ('453', 'Croagunk', NULL, FALSE, FALSE, FALSE, NULL),
  ('454', 'Toxicroak', NULL, FALSE, FALSE, FALSE, NULL),
  ('455', 'Carnivine', NULL, FALSE, FALSE, FALSE, NULL),
  ('456', 'Finneon', NULL, FALSE, FALSE, FALSE, NULL),
  ('457', 'Lumineon', NULL, FALSE, FALSE, FALSE, NULL),
  ('458', 'Mantyke', NULL, FALSE, FALSE, FALSE, NULL),
  ('459', 'Snover', NULL, FALSE, FALSE, FALSE, NULL),
  ('460', 'Abomasnow', NULL, FALSE, FALSE, FALSE, NULL),
  ('460', 'Abomasnow', 'Mega Abomasnow', FALSE, FALSE, TRUE, NULL),
  ('461', 'Weavile', NULL, FALSE, FALSE, FALSE, NULL),
  ('462', 'Magnezone', NULL, FALSE, FALSE, FALSE, NULL),
  ('463', 'Lickilicky', NULL, FALSE, FALSE, FALSE, NULL),
  ('464', 'Rhyperior', NULL, FALSE, FALSE, FALSE, NULL),
  ('465', 'Tangrowth', NULL, FALSE, FALSE, FALSE, NULL),
  ('466', 'Electivire', NULL, FALSE, FALSE, FALSE, NULL),
  ('467', 'Magmortar', NULL, FALSE, FALSE, FALSE, NULL),
  ('468', 'Togekiss', NULL, FALSE, FALSE, FALSE, NULL),
  ('469', 'Yanmega', NULL, FALSE, FALSE, FALSE, NULL),
  ('470', 'Leafeon', NULL, FALSE, FALSE, FALSE, NULL),
  ('471', 'Glaceon', NULL, FALSE, FALSE, FALSE, NULL),
  ('472', 'Gliscor', NULL, FALSE, FALSE, FALSE, NULL),
  ('473', 'Mamoswine', NULL, FALSE, FALSE, FALSE, NULL),
  ('474', 'Porygon-Z', NULL, FALSE, FALSE, FALSE, NULL),
  ('475', 'Gallade', NULL, FALSE, FALSE, FALSE, NULL),
  ('475', 'Gallade', 'Mega Gallade', FALSE, FALSE, TRUE, NULL),
  ('476', 'Probopass', NULL, FALSE, FALSE, FALSE, NULL),
  ('477', 'Dusknoir', NULL, FALSE, FALSE, FALSE, NULL),
  ('478', 'Froslass', NULL, FALSE, FALSE, FALSE, NULL),
  ('479', 'Rotom', NULL, FALSE, FALSE, FALSE, NULL),
  ('479', 'Rotom', 'Heat Rotom', FALSE, FALSE, FALSE, NULL),
  ('479', 'Rotom', 'Wash Rotom', FALSE, FALSE, FALSE, NULL),
  ('479', 'Rotom', 'Frost Rotom', FALSE, FALSE, FALSE, NULL),
  ('479', 'Rotom', 'Fan Rotom', FALSE, FALSE, FALSE, NULL),
  ('479', 'Rotom', 'Mow Rotom', FALSE, FALSE, FALSE, NULL),
  ('480', 'Uxie', NULL, TRUE, FALSE, FALSE, NULL),
  ('481', 'Mesprit', NULL, TRUE, FALSE, FALSE, NULL),
  ('482', 'Azelf', NULL, TRUE, FALSE, FALSE, NULL),
  ('483', 'Dialga', NULL, TRUE, FALSE, FALSE, NULL),
  ('484', 'Palkia', NULL, TRUE, FALSE, FALSE, NULL),
  ('485', 'Heatran', NULL, TRUE, FALSE, FALSE, NULL),
  ('486', 'Regigigas', NULL, TRUE, FALSE, FALSE, NULL),
  ('487', 'Giratina', 'Altered Forme', TRUE, FALSE, FALSE, NULL),
  ('487', 'Giratina', 'Origin Forme', TRUE, FALSE, FALSE, NULL),
  ('488', 'Cresselia', NULL, TRUE, FALSE, FALSE, NULL),
  ('489', 'Phione', NULL, FALSE, TRUE, FALSE, NULL),
  ('490', 'Manaphy', NULL, FALSE, TRUE, FALSE, NULL),
  ('491', 'Darkrai', NULL, FALSE, TRUE, FALSE, NULL),
  ('492', 'Shaymin', 'Land Forme', FALSE, TRUE, FALSE, NULL),
  ('492', 'Shaymin', 'Sky Forme', FALSE, TRUE, FALSE, NULL),
  ('493', 'Arceus', NULL, TRUE, FALSE, FALSE, NULL),
  ('494', 'Victini', NULL, FALSE, TRUE, FALSE, NULL),
  ('495', 'Snivy', NULL, FALSE, FALSE, FALSE, NULL),
  ('496', 'Servine', NULL, FALSE, FALSE, FALSE, NULL),
  ('497', 'Serperior', NULL, FALSE, FALSE, FALSE, NULL),
  ('498', 'Tepig', NULL, FALSE, FALSE, FALSE, NULL),
  ('499', 'Pignite', NULL, FALSE, FALSE, FALSE, NULL),
  ('500', 'Emboar', NULL, FALSE, FALSE, FALSE, NULL),
  ('501', 'Oshawott', NULL, FALSE, FALSE, FALSE, NULL),
  ('502', 'Dewott', NULL, FALSE, FALSE, FALSE, NULL),
  ('503', 'Samurott', NULL, FALSE, FALSE, FALSE, NULL),
  ('504', 'Patrat', NULL, FALSE, FALSE, FALSE, NULL),
  ('505', 'Watchog', NULL, FALSE, FALSE, FALSE, NULL),
  ('506', 'Lillipup', NULL, FALSE, FALSE, FALSE, NULL),
  ('507', 'Herdier', NULL, FALSE, FALSE, FALSE, NULL),
  ('508', 'Stoutland', NULL, FALSE, FALSE, FALSE, NULL),
  ('509', 'Purrloin', NULL, FALSE, FALSE, FALSE, NULL),
  ('510', 'Liepard', NULL, FALSE, FALSE, FALSE, NULL),
  ('511', 'Pansage', NULL, FALSE, FALSE, FALSE, NULL),
  ('512', 'Simisage', NULL, FALSE, FALSE, FALSE, NULL),
  ('513', 'Pansear', NULL, FALSE, FALSE, FALSE, NULL),
  ('514', 'Simisear', NULL, FALSE, FALSE, FALSE, NULL),
  ('515', 'Panpour', NULL, FALSE, FALSE, FALSE, NULL),
  ('516', 'Simipour', NULL, FALSE, FALSE, FALSE, NULL),
  ('517', 'Munna', NULL, FALSE, FALSE, FALSE, NULL),
  ('518', 'Musharna', NULL, FALSE, FALSE, FALSE, NULL),
  ('519', 'Pidove', NULL, FALSE, FALSE, FALSE, NULL),
  ('520', 'Tranquill', NULL, FALSE, FALSE, FALSE, NULL),
  ('521', 'Unfezant', NULL, FALSE, FALSE, FALSE, NULL),
  ('522', 'Blitzle', NULL, FALSE, FALSE, FALSE, NULL),
  ('523', 'Zebstrika', NULL, FALSE, FALSE, FALSE, NULL),
  ('524', 'Roggenrola', NULL, FALSE, FALSE, FALSE, NULL),
  ('525', 'Boldore', NULL, FALSE, FALSE, FALSE, NULL),
  ('526', 'Gigalith', NULL, FALSE, FALSE, FALSE, NULL),
  ('527', 'Woobat', NULL, FALSE, FALSE, FALSE, NULL),
  ('528', 'Swoobat', NULL, FALSE, FALSE, FALSE, NULL),
  ('529', 'Drilbur', NULL, FALSE, FALSE, FALSE, NULL),
  ('530', 'Excadrill', NULL, FALSE, FALSE, FALSE, NULL),
  ('531', 'Audino', NULL, FALSE, FALSE, FALSE, NULL),
  ('531', 'Audino', 'Mega Audino', FALSE, FALSE, TRUE, NULL),
  ('532', 'Timburr', NULL, FALSE, FALSE, FALSE, NULL),
  ('533', 'Gurdurr', NULL, FALSE, FALSE, FALSE, NULL),
  ('534', 'Conkeldurr', NULL, FALSE, FALSE, FALSE, NULL),
  ('535', 'Tympole', NULL, FALSE, FALSE, FALSE, NULL),
  ('536', 'Palpitoad', NULL, FALSE, FALSE, FALSE, NULL),
  ('537', 'Seismitoad', NULL, FALSE, FALSE, FALSE, NULL),
  ('538', 'Throh', NULL, FALSE, FALSE, FALSE, NULL),
  ('539', 'Sawk', NULL, FALSE, FALSE, FALSE, NULL),
  ('540', 'Sewaddle', NULL, FALSE, FALSE, FALSE, NULL),
  ('541', 'Swadloon', NULL, FALSE, FALSE, FALSE, NULL),
  ('542', 'Leavanny', NULL, FALSE, FALSE, FALSE, NULL),
  ('543', 'Venipede', NULL, FALSE, FALSE, FALSE, NULL),
  ('544', 'Whirlipede', NULL, FALSE, FALSE, FALSE, NULL),
  ('545', 'Scolipede', NULL, FALSE, FALSE, FALSE, NULL),
  ('546', 'Cottonee', NULL, FALSE, FALSE, FALSE, NULL),
  ('547', 'Whimsicott', NULL, FALSE, FALSE, FALSE, NULL),
  ('548', 'Petilil', NULL, FALSE, FALSE, FALSE, NULL),
  ('549', 'Lilligant', NULL, FALSE, FALSE, FALSE, NULL),
  ('550', 'Basculin', 'Red-Striped Form', FALSE, FALSE, FALSE, NULL),
  ('550', 'Basculin', 'Blue-Striped Form', FALSE, FALSE, FALSE, NULL),
  ('551', 'Sandile', NULL, FALSE, FALSE, FALSE, NULL),
  ('552', 'Krokorok', NULL, FALSE, FALSE, FALSE, NULL),
  ('553', 'Krookodile', NULL, FALSE, FALSE, FALSE, NULL),
  ('554', 'Darumaka', NULL, FALSE, FALSE, FALSE, NULL),
  ('555', 'Darmanitan', 'Standard Mode', FALSE, FALSE, FALSE, NULL),
  ('555', 'Darmanitan', 'Zen Mode', FALSE, FALSE, FALSE, NULL),
  ('556', 'Maractus', NULL, FALSE, FALSE, FALSE, NULL),
  ('557', 'Dwebble', NULL, FALSE, FALSE, FALSE, NULL),
  ('558', 'Crustle', NULL, FALSE, FALSE, FALSE, NULL),
  ('559', 'Scraggy', NULL, FALSE, FALSE, FALSE, NULL),
  ('560', 'Scrafty', NULL, FALSE, FALSE, FALSE, NULL),
  ('561', 'Sigilyph', NULL, FALSE, FALSE, FALSE, NULL),
  ('562', 'Yamask', NULL, FALSE, FALSE, FALSE, NULL),
  ('563', 'Cofagrigus', NULL, FALSE, FALSE, FALSE, NULL),
  ('564', 'Tirtouga', NULL, FALSE, FALSE, FALSE, NULL),
  ('565', 'Carracosta', NULL, FALSE, FALSE, FALSE, NULL),
  ('566', 'Archen', NULL, FALSE, FALSE, FALSE, NULL),
  ('567', 'Archeops', NULL, FALSE, FALSE, FALSE, NULL),
  ('568', 'Trubbish', NULL, FALSE, FALSE, FALSE, NULL),
  ('569', 'Garbodor', NULL, FALSE, FALSE, FALSE, NULL),
  ('570', 'Zorua', NULL, FALSE, FALSE, FALSE, NULL),
  ('571', 'Zoroark', NULL, FALSE, FALSE, FALSE, NULL),
  ('572', 'Minccino', NULL, FALSE, FALSE, FALSE, NULL),
  ('573', 'Cinccino', NULL, FALSE, FALSE, FALSE, NULL),
  ('574', 'Gothita', NULL, FALSE, FALSE, FALSE, NULL),
  ('575', 'Gothorita', NULL, FALSE, FALSE, FALSE, NULL),
  ('576', 'Gothitelle', NULL, FALSE, FALSE, FALSE, NULL),
  ('577', 'Solosis', NULL, FALSE, FALSE, FALSE, NULL),
  ('578', 'Duosion', NULL, FALSE, FALSE, FALSE, NULL),
  ('579', 'Reuniclus', NULL, FALSE, FALSE, FALSE, NULL),
  ('580', 'Ducklett', NULL, FALSE, FALSE, FALSE, NULL),
  ('581', 'Swanna', NULL, FALSE, FALSE, FALSE, NULL),
  ('582', 'Vanillite', NULL, FALSE, FALSE, FALSE, NULL),
  ('583', 'Vanillish', NULL, FALSE, FALSE, FALSE, NULL),
  ('584', 'Vanilluxe', NULL, FALSE, FALSE, FALSE, NULL),
  ('585', 'Deerling', NULL, FALSE, FALSE, FALSE, NULL),
  ('586', 'Sawsbuck', NULL, FALSE, FALSE, FALSE, NULL),
  ('587', 'Emolga', NULL, FALSE, FALSE, FALSE, NULL),
  ('588', 'Karrablast', NULL, FALSE, FALSE, FALSE, NULL),
  ('589', 'Escavalier', NULL, FALSE, FALSE, FALSE, NULL),
  ('590', 'Foongus', NULL, FALSE, FALSE, FALSE, NULL),
  ('591', 'Amoonguss', NULL, FALSE, FALSE, FALSE, NULL),
  ('592', 'Frillish', NULL, FALSE, FALSE, FALSE, NULL),
  ('593', 'Jellicent', NULL, FALSE, FALSE, FALSE, NULL),
  ('594', 'Alomomola', NULL, FALSE, FALSE, FALSE, NULL),
  ('595', 'Joltik', NULL, FALSE, FALSE, FALSE, NULL),
  ('596', 'Galvantula', NULL, FALSE, FALSE, FALSE, NULL),
  ('597', 'Ferroseed', NULL, FALSE, FALSE, FALSE, NULL),
  ('598', 'Ferrothorn', NULL, FALSE, FALSE, FALSE, NULL),
  ('599', 'Klink', NULL, FALSE, FALSE, FALSE, NULL),
  ('600', 'Klang', NULL, FALSE, FALSE, FALSE, NULL),
  ('601', 'Klinklang', NULL, FALSE, FALSE, FALSE, NULL),
  ('602', 'Tynamo', NULL, FALSE, FALSE, FALSE, NULL),
  ('603', 'Eelektrik', NULL, FALSE, FALSE, FALSE, NULL),
  ('604', 'Eelektross', NULL, FALSE, FALSE, FALSE, NULL),
  ('605', 'Elgyem', NULL, FALSE, FALSE, FALSE, NULL),
  ('606', 'Beheeyem', NULL, FALSE, FALSE, FALSE, NULL),
  ('607', 'Litwick', NULL, FALSE, FALSE, FALSE, NULL),
  ('608', 'Lampent', NULL, FALSE, FALSE, FALSE, NULL),
  ('609', 'Chandelure', NULL, FALSE, FALSE, FALSE, NULL),
  ('610', 'Axew', NULL, FALSE, FALSE, FALSE, NULL),
  ('611', 'Fraxure', NULL, FALSE, FALSE, FALSE, NULL),
  ('612', 'Haxorus', NULL, FALSE, FALSE, FALSE, NULL),
  ('613', 'Cubchoo', NULL, FALSE, FALSE, FALSE, NULL),
  ('614', 'Beartic', NULL, FALSE, FALSE, FALSE, NULL),
  ('615', 'Cryogonal', NULL, FALSE, FALSE, FALSE, NULL),
  ('616', 'Shelmet', NULL, FALSE, FALSE, FALSE, NULL),
  ('617', 'Accelgor', NULL, FALSE, FALSE, FALSE, NULL),
  ('618', 'Stunfisk', NULL, FALSE, FALSE, FALSE, NULL),
  ('619', 'Mienfoo', NULL, FALSE, FALSE, FALSE, NULL),
  ('620', 'Mienshao', NULL, FALSE, FALSE, FALSE, NULL),
  ('621', 'Druddigon', NULL, FALSE, FALSE, FALSE, NULL),
  ('622', 'Golett', NULL, FALSE, FALSE, FALSE, NULL),
  ('623', 'Golurk', NULL, FALSE, FALSE, FALSE, NULL),
  ('624', 'Pawniard', NULL, FALSE, FALSE, FALSE, NULL),
  ('625', 'Bisharp', NULL, FALSE, FALSE, FALSE, NULL),
  ('626', 'Bouffalant', NULL, FALSE, FALSE, FALSE, NULL),
  ('627', 'Rufflet', NULL, FALSE, FALSE, FALSE, NULL),
  ('628', 'Braviary', NULL, FALSE, FALSE, FALSE, NULL),
  ('629', 'Vullaby', NULL, FALSE, FALSE, FALSE, NULL),
  ('630', 'Mandibuzz', NULL, FALSE, FALSE, FALSE, NULL),
  ('631', 'Heatmor', NULL, FALSE, FALSE, FALSE, NULL),
  ('632', 'Durant', NULL, FALSE, FALSE, FALSE, NULL),
  ('633', 'Deino', NULL, FALSE, FALSE, FALSE, NULL),
  ('634', 'Zweilous', NULL, FALSE, FALSE, FALSE, NULL),
  ('635', 'Hydreigon', NULL, FALSE, FALSE, FALSE, NULL),
  ('636', 'Larvesta', NULL, FALSE, FALSE, FALSE, NULL),
  ('637', 'Volcarona', NULL, FALSE, FALSE, FALSE, NULL),
  ('638', 'Cobalion', NULL, TRUE, FALSE, FALSE, NULL),
  ('639', 'Terrakion', NULL, TRUE, FALSE, FALSE, NULL),
  ('640', 'Virizion', NULL, TRUE, FALSE, FALSE, NULL),
  ('641', 'Tornadus', 'Incarnate Forme', TRUE, FALSE, FALSE, NULL),
  ('641', 'Tornadus', 'Therian Forme', TRUE, FALSE, FALSE, NULL),
  ('642', 'Thundurus', 'Incarnate Forme', TRUE, FALSE, FALSE, NULL),
  ('642', 'Thundurus', 'Therian Forme', TRUE, FALSE, FALSE, NULL),
  ('643', 'Reshiram', NULL, TRUE, FALSE, FALSE, NULL),
  ('644', 'Zekrom', NULL, TRUE, FALSE, FALSE, NULL),
  ('645', 'Landorus', 'Incarnate Forme', TRUE, FALSE, FALSE, NULL),
  ('645', 'Landorus', 'Therian Forme', TRUE, FALSE, FALSE, NULL),
  ('646', 'Kyurem', NULL, TRUE, FALSE, FALSE, NULL),
  ('646', 'Kyurem', 'Black Kyurem', NULL, TRUE, FALSE, FALSE, NULL),
  ('646', 'Kyurem', 'White Kyurem', NULL, TRUE, FALSE, FALSE, NULL),
  ('647', 'Keldeo', 'Ordinary Forme', FALSE, TRUE, FALSE, NULL),
  ('647', 'Keldeo', 'Resolute Forme', FALSE, TRUE, FALSE, NULL),
  ('648', 'Meloetta', 'Aria Forme', FALSE, TRUE, FALSE, NULL),
  ('648', 'Meloetta', 'Pirouette Forme', FALSE, TRUE, FALSE, NULL),
  ('649', 'Genesect', NULL, FALSE, TRUE, FALSE, NULL),
  ('650', 'Chespin', NULL, FALSE, FALSE, FALSE, NULL),
  ('651', 'Quilladin', NULL, FALSE, FALSE, FALSE, NULL),
  ('652', 'Chesnaught', NULL, FALSE, FALSE, FALSE, NULL),
  ('653', 'Fennekin', NULL, FALSE, FALSE, FALSE, NULL),
  ('654', 'Braixen', NULL, FALSE, FALSE, FALSE, NULL),
  ('655', 'Delphox', NULL, FALSE, FALSE, FALSE, NULL),
  ('656', 'Froakie', NULL, FALSE, FALSE, FALSE, NULL),
  ('657', 'Frogadier', NULL, FALSE, FALSE, FALSE, NULL),
  ('658', 'Greninja', NULL, FALSE, FALSE, FALSE, NULL),
  ('658', 'Greninja', 'Ash-Greninja', FALSE, FALSE, FALSE, NULL),
  ('659', 'Bunnelby', NULL, FALSE, FALSE, FALSE, NULL),
  ('660', 'Diggersby', NULL, FALSE, FALSE, FALSE, NULL),
  ('661', 'Fletchling', NULL, FALSE, FALSE, FALSE, NULL),
  ('662', 'Fletchinder', NULL, FALSE, FALSE, FALSE, NULL),
  ('663', 'Talonflame', NULL, FALSE, FALSE, FALSE, NULL),
  ('664', 'Scatterbug', NULL, FALSE, FALSE, FALSE, NULL),
  ('665', 'Spewpa', NULL, FALSE, FALSE, FALSE, NULL),
  ('666', 'Vivillon', NULL, FALSE, FALSE, FALSE, NULL),
  ('667', 'Litleo', NULL, FALSE, FALSE, FALSE, NULL),
  ('668', 'Pyroar', NULL, FALSE, FALSE, FALSE, NULL),
  ('669', 'Flabébé', NULL, FALSE, FALSE, FALSE, NULL),
  ('670', 'Floette', NULL, FALSE, FALSE, FALSE, NULL),
  ('671', 'Florges', NULL, FALSE, FALSE, FALSE, NULL),
  ('672', 'Skiddo', NULL, FALSE, FALSE, FALSE, NULL),
  ('673', 'Gogoat', NULL, FALSE, FALSE, FALSE, NULL),
  ('674', 'Pancham', NULL, FALSE, FALSE, FALSE, NULL),
  ('675', 'Pangoro', NULL, FALSE, FALSE, FALSE, NULL),
  ('676', 'Furfrou', NULL, FALSE, FALSE, FALSE, NULL),
  ('677', 'Espurr', NULL, FALSE, FALSE, FALSE, NULL),
  ('678', 'Meowstic', 'Male', FALSE, FALSE, FALSE, NULL),
  ('678', 'Meowstic', 'Female', FALSE, FALSE, FALSE, NULL),
  ('679', 'Honedge', NULL, FALSE, FALSE, FALSE, NULL),
  ('680', 'Doublade', NULL, FALSE, FALSE, FALSE, NULL),
  ('681', 'Aegislash', 'Blade Forme', FALSE, FALSE, FALSE, NULL),
  ('681', 'Aegislash', 'Shield Forme', FALSE, FALSE, FALSE, NULL),
  ('682', 'Spritzee', NULL, FALSE, FALSE, FALSE, NULL),
  ('683', 'Aromatisse', NULL, FALSE, FALSE, FALSE, NULL),
  ('684', 'Swirlix', NULL, FALSE, FALSE, FALSE, NULL),
  ('685', 'Slurpuff', NULL, FALSE, FALSE, FALSE, NULL),
  ('686', 'Inkay', NULL, FALSE, FALSE, FALSE, NULL),
  ('687', 'Malamar', NULL, FALSE, FALSE, FALSE, NULL),
  ('688', 'Binacle', NULL, FALSE, FALSE, FALSE, NULL),
  ('689', 'Barbaracle', NULL, FALSE, FALSE, FALSE, NULL),
  ('690', 'Skrelp', NULL, FALSE, FALSE, FALSE, NULL),
  ('691', 'Dragalge', NULL, FALSE, FALSE, FALSE, NULL),
  ('692', 'Clauncher', NULL, FALSE, FALSE, FALSE, NULL),
  ('693', 'Clawitzer', NULL, FALSE, FALSE, FALSE, NULL),
  ('694', 'Helioptile', NULL, FALSE, FALSE, FALSE, NULL),
  ('695', 'Heliolisk', NULL, FALSE, FALSE, FALSE, NULL),
  ('696', 'Tyrunt', NULL, FALSE, FALSE, FALSE, NULL),
  ('697', 'Tyrantrum', NULL, FALSE, FALSE, FALSE, NULL),
  ('698', 'Amaura', NULL, FALSE, FALSE, FALSE, NULL),
  ('699', 'Aurorus', NULL, FALSE, FALSE, FALSE, NULL),
  ('700', 'Sylveon', NULL, FALSE, FALSE, FALSE, NULL),
  ('701', 'Hawlucha', NULL, FALSE, FALSE, FALSE, NULL),
  ('702', 'Dedenne', NULL, FALSE, FALSE, FALSE, NULL),
  ('703', 'Carbink', NULL, FALSE, FALSE, FALSE, NULL),
  ('704', 'Goomy', NULL, FALSE, FALSE, FALSE, NULL),
  ('705', 'Sliggoo', NULL, FALSE, FALSE, FALSE, NULL),
  ('706', 'Goodra', NULL, FALSE, FALSE, FALSE, NULL),
  ('707', 'Klefki', NULL, FALSE, FALSE, FALSE, NULL),
  ('708', 'Phantump', NULL, FALSE, FALSE, FALSE, NULL),
  ('709', 'Trevenant', NULL, FALSE, FALSE, FALSE, NULL),
  ('710', 'Pumpkaboo', 'Average Size', NULL, FALSE, FALSE, FALSE, NULL),
  ('710', 'Pumpkaboo', 'Small Size', NULL, FALSE, FALSE, FALSE, NULL),
  ('710', 'Pumpkaboo', 'Large Size', NULL, FALSE, FALSE, FALSE, NULL),
  ('710', 'Pumpkaboo', 'Super Size', NULL, FALSE, FALSE, FALSE, NULL),
  ('711', 'Gourgeist', 'Average Size', NULL, FALSE, FALSE, FALSE, NULL),
  ('711', 'Gourgeist', 'Small Size', NULL, FALSE, FALSE, FALSE, NULL),
  ('711', 'Gourgeist', 'Large Size', NULL, FALSE, FALSE, FALSE, NULL),
  ('711', 'Gourgeist', 'Super Size', NULL, FALSE, FALSE, FALSE, NULL),
  ('712', 'Bergmite', NULL, FALSE, FALSE, FALSE, NULL),
  ('713', 'Avalugg', NULL, FALSE, FALSE, FALSE, NULL),
  ('714', 'Noibat', NULL, FALSE, FALSE, FALSE, NULL),
  ('715', 'Noivern', NULL, FALSE, FALSE, FALSE, NULL),
  ('716', 'Xerneas', NULL, TRUE, FALSE, FALSE, NULL),
  ('717', 'Yveltal', NULL, TRUE, FALSE, FALSE, NULL),
  ('718', 'Zygarde', '50% Forme', TRUE, FALSE, FALSE, NULL),
  ('718', 'Zygarde', '10% Forme', TRUE, FALSE, FALSE, NULL),
  ('718', 'Zygarde', 'Complete Forme', TRUE, FALSE, FALSE, NULL),
  ('719', 'Diancie', NULL, FALSE, TRUE, FALSE, NULL),
  ('719', 'Diancie', 'Mega Diancie', FALSE, TRUE, TRUE, NULL),
  ('720', 'Hoopa', 'Hoopa Confined', FALSE, TRUE, FALSE, NULL),
  ('720', 'Hoopa', 'Hoopa Unbound', FALSE, TRUE, FALSE, NULL),
  ('721', 'Volcanion', NULL, FALSE, TRUE, FALSE, NULL),
  ('722', 'Rowlet', NULL, FALSE, FALSE, FALSE, NULL),
  ('723', 'Dartrix', NULL, FALSE, FALSE, FALSE, NULL),
  ('724', 'Decidueye', NULL, FALSE, FALSE, FALSE, NULL),
  ('725', 'Litten', NULL, FALSE, FALSE, FALSE, NULL),
  ('726', 'Torracat', NULL, FALSE, FALSE, FALSE, NULL),
  ('727', 'Incineroar', NULL, FALSE, FALSE, FALSE, NULL),
  ('728', 'Popplio', NULL, FALSE, FALSE, FALSE, NULL),
  ('729', 'Brionne', NULL, FALSE, FALSE, FALSE, NULL),
  ('730', 'Primarina', NULL, FALSE, FALSE, FALSE, NULL),
  ('731', 'Pikipek', NULL, FALSE, FALSE, FALSE, NULL),
  ('732', 'Trumbeak', NULL, FALSE, FALSE, FALSE, NULL),
  ('733', 'Toucannon', NULL, FALSE, FALSE, FALSE, NULL),
  ('734', 'Yungoos', NULL, FALSE, FALSE, FALSE, NULL),
  ('735', 'Gumshoos', NULL, FALSE, FALSE, FALSE, NULL),
  ('736', 'Grubbin', NULL, FALSE, FALSE, FALSE, NULL),
  ('737', 'Charjabug', NULL, FALSE, FALSE, FALSE, NULL),
  ('738', 'Vikavolt', NULL, FALSE, FALSE, FALSE, NULL),
  ('739', 'Crabrawler', NULL, FALSE, FALSE, FALSE, NULL),
  ('740', 'Crabominable', NULL, FALSE, FALSE, FALSE, NULL),
  ('741', 'Oricorio', 'Baile Style', FALSE, FALSE, FALSE, NULL),
  ('741', 'Oricorio', 'Pom-Pom Style', FALSE, FALSE, FALSE, NULL),
  ('741', 'Oricorio', 'Pa''u Style', FALSE, FALSE, FALSE, NULL),
  ('741', 'Oricorio', 'Sensu Style', FALSE, FALSE, FALSE, NULL),
  ('742', 'Cutiefly', NULL, FALSE, FALSE, FALSE, NULL),
  ('743', 'Ribombee', NULL, FALSE, FALSE, FALSE, NULL),
  ('744', 'Rockruff', NULL, FALSE, FALSE, FALSE, NULL),
  ('744', 'Rockruff', 'Own Tempo Rockruff', FALSE, FALSE, FALSE, NULL),
  ('744', 'Lycanroc', 'Midday Form', FALSE, FALSE, FALSE, NULL),
  ('744', 'Lycanroc', 'Midnight Form', FALSE, FALSE, FALSE, NULL),
  ('744', 'Lycanroc', 'Dusk Form', FALSE, FALSE, FALSE, NULL),
  ('746', 'Wishiwashi', 'Solo Form', FALSE, FALSE, FALSE, NULL),
  ('746', 'Wishiwashi', 'School Form', FALSE, FALSE, FALSE, NULL),
  ('747', 'Mareanie', NULL, FALSE, FALSE, FALSE, NULL),
  ('748', 'Toxapex', NULL, FALSE, FALSE, FALSE, NULL),
  ('749', 'Mudbray', NULL, FALSE, FALSE, FALSE, NULL),
  ('750', 'Mudsdale', NULL, FALSE, FALSE, FALSE, NULL),
  ('751', 'Dewpider', NULL, FALSE, FALSE, FALSE, NULL),
  ('752', 'Araquanid', NULL, FALSE, FALSE, FALSE, NULL),
  ('753', 'Fomantis', NULL, FALSE, FALSE, FALSE, NULL),
  ('754', 'Lurantis', NULL, FALSE, FALSE, FALSE, NULL),
  ('755', 'Morelull', NULL, FALSE, FALSE, FALSE, NULL),
  ('756', 'Shiinotic', NULL, FALSE, FALSE, FALSE, NULL),
  ('757', 'Salandit', NULL, FALSE, FALSE, FALSE, NULL),
  ('758', 'Salazzle', NULL, FALSE, FALSE, FALSE, NULL),
  ('759', 'Stufful', NULL, FALSE, FALSE, FALSE, NULL),
  ('760', 'Bewear', NULL, FALSE, FALSE, FALSE, NULL),
  ('761', 'Bounsweet', NULL, FALSE, FALSE, FALSE, NULL),
  ('762', 'Steenee', NULL, FALSE, FALSE, FALSE, NULL),
  ('763', 'Tsareena', NULL, FALSE, FALSE, FALSE, NULL),
  ('764', 'Comfey', NULL, FALSE, FALSE, FALSE, NULL),
  ('765', 'Oranguru', NULL, FALSE, FALSE, FALSE, NULL),
  ('766', 'Passimian', NULL, FALSE, FALSE, FALSE, NULL),
  ('767', 'Wimpod', NULL, FALSE, FALSE, FALSE, NULL),
  ('768', 'Golisopod', NULL, FALSE, FALSE, FALSE, NULL),
  ('769', 'Sandygast', NULL, FALSE, FALSE, FALSE, NULL),
  ('770', 'Palossand', NULL, FALSE, FALSE, FALSE, NULL),
  ('771', 'Pyukumuku', NULL, FALSE, FALSE, FALSE, NULL),
  ('772', 'Type: Null', NULL, FALSE, FALSE, FALSE, NULL),
  ('773', 'Silvally', NULL, FALSE, FALSE, FALSE, NULL),
  ('774', 'Minior', 'Meteor Form', FALSE, FALSE, FALSE, NULL),
  ('774', 'Minior', 'Core Form', FALSE, FALSE, FALSE, NULL),
  ('775', 'Komala', NULL, FALSE, FALSE, FALSE, NULL),
  ('776', 'Turtonator', NULL, FALSE, FALSE, FALSE, NULL),
  ('777', 'Togedemaru', NULL, FALSE, FALSE, FALSE, NULL),
  ('778', 'Mimikyu', NULL, FALSE, FALSE, FALSE, NULL),
  ('779', 'Bruxish', NULL, FALSE, FALSE, FALSE, NULL),
  ('780', 'Drampa', NULL, FALSE, FALSE, FALSE, NULL),
  ('781', 'Dhelmise', NULL, FALSE, FALSE, FALSE, NULL),
  ('782', 'Jangmo-o', NULL, FALSE, FALSE, FALSE, NULL),
  ('783', 'Hakamo-o', NULL, FALSE, FALSE, FALSE, NULL),
  ('784', 'Kommo-o', NULL, FALSE, FALSE, FALSE, NULL),
  ('785', 'Tapu Koko', NULL, TRUE, FALSE, FALSE, NULL),
  ('786', 'Tapu Lele', NULL, TRUE, FALSE, FALSE, NULL),
  ('787', 'Tapu Bulu', NULL, TRUE, FALSE, FALSE, NULL),
  ('788', 'Tapu Fini', NULL, TRUE, FALSE, FALSE, NULL),
  ('789', 'Cosmog', NULL, TRUE, FALSE, FALSE, NULL),
  ('790', 'Cosmoem', NULL, TRUE, FALSE, FALSE, NULL),
  ('791', 'Solgaleo', NULL, TRUE, FALSE, FALSE, NULL),
  ('792', 'Lunala', NULL, TRUE, FALSE, FALSE, NULL),
  ('793', 'Nihilego', NULL, TRUE, FALSE, FALSE, NULL),
  ('794', 'Buzzwole', NULL, TRUE, FALSE, FALSE, NULL),
  ('795', 'Pheromosa', NULL, TRUE, FALSE, FALSE, NULL),
  ('796', 'Xurkitree', NULL, TRUE, FALSE, FALSE, NULL),
  ('797', 'Celesteela', NULL, TRUE, FALSE, FALSE, NULL),
  ('798', 'Kartana', NULL, TRUE, FALSE, FALSE, NULL),
  ('799', 'Guzzlord', NULL, TRUE, FALSE, FALSE, NULL),
  ('800', 'Necrozma', NULL, TRUE, FALSE, FALSE, NULL),
  ('800', 'Necrozma', 'Dusk Mane Necrozma', TRUE, FALSE, FALSE, NULL),
  ('800', 'Necrozma', 'Dawn Wings Necrozma', TRUE, FALSE, FALSE, NULL),
  ('800', 'Necrozma', 'Ultra Necrozma', FALSE, TRUE, FALSE, NULL),
  ('801', 'Magearna', NULL, FALSE, TRUE, FALSE, NULL),
  ('802', 'Marshadow', NULL, FALSE, TRUE, FALSE, NULL),
  ('803', 'Poipole', NULL, TRUE, FALSE, FALSE, NULL),
  ('804', 'Naganadel', NULL, TRUE, FALSE, FALSE, NULL),
  ('805', 'Stakataka', NULL, TRUE, FALSE, FALSE, NULL),
  ('806', 'Blacephalon', NULL, TRUE, FALSE, FALSE, NULL),
  ('807', 'Zeraora', NULL, FALSE, TRUE, FALSE, NULL);
