version: '3.7'
services:
  app-service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - app-database
    networks:
      app-network:
        aliases:
          - app-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${DATABASE}:5432/rank?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=${DATABASE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATABASE_PASSWORD}

  app-database:
    image: postgres:11.3-alpine
    networks:
      app-network:
        aliases:
          - app-database
    restart: always
    environment:
      POSTGRES_USERNAME: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data/
      - ./createDatabase.sql:/docker-entrypoint-initdb.d/createDatabase.sql # Alphabetical order -- use leading numbers
    ports:
      - 5432
volumes:
  db-data:
networks:
  app-network:
