# TODO Figure out profiles and environment
spring:
  datasource:
    jndi-name: java:/comp/env/jdbc/postgres
    url: jdbc:postgresql://localhost:5432/Ikanobuntai
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
