package com.immanuelqrw.ikanobuntai.api.entity

enum class Title(val gruntRequirement: Int = 0) {
    GYM_LEADER(3),
    LEAGUE_RANKED_05(6),
    ELITE_FOUR(8),
    LEAGUE_BARON,
    LEAGUE_CHAMPION(4),
    ARENA_TYCOON(6),
    DOME_ACE(6),
    FACTORY_HEAD(6),
    PALACE_MAVEN(6),
    PIKE_QUEEN(6),
    PYRAMID_KING(6),
    SALON_MAIDEN(6),
    TOWER_TYCOON(6),
    ARCADE_STAR(6),
    CASTLE_VALET(6),
    HALL_MATRON(6),
    WORLD_RANKED_10(1),
    WORLD_RANKED_09(1),
    WORLD_RANKED_08(1),
    WORLD_RANKED_07(1),
    WORLD_RANKED_06(1),
    WORLD_RANKED_05(1),
    WORLD_RANKED_04(1),
    WORLD_RANKED_03(1),
    WORLD_RANKED_02(1),
    WORLD_RANKED_01(1),
    WORLD_NOBLE,
    WORLD_CHAMPION(4)
}
